version: '2'
services:
    cce-app:
        image: cce
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://cce-mysql:3306/cce?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=cce-elasticsearch:9300
        ports:
            - 8080:8080
    cce-mysql:
        extends:
            file: mysql.yml
            service: cce-mysql
    cce-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: cce-elasticsearch
